on:
  push:
    branches:
      - main

jobs:
  build:
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@v1
      - uses: Swatinem/rust-cache@v2
      - run: |
          cargo build --release --target aarch64-unknown-linux-gnu
          cargo build --release --target x86_64-unknown-linux-gnu
