on:
  push:
    branches:
      - main

jobs:
  build-aarch64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: build
        uses: ./.github/actions/release-build
        with:
          target: aarch64-unknown-linux-gnu
    outputs:
      sha256sum: ${{ steps.build.outputs.sha256sum }}

  build-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: build
        uses: ./.github/actions/release-build
        with:
          target: x86_64-unknown-linux-gnu
    outputs:
      sha256sum: ${{ steps.build.outputs.sha256sum }}

  checksum:
    runs-on: ubuntu-latest
    needs: [build-aarch64, build-x86_64]
    steps:
      - run: |
          echo ${{ needs.build-aarch64.outputs.sha256sum }}
          echo ${{ needs.build-x86_64.outputs.sha256sum }}
