on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create ${{ github.ref_name }}

  build-aarch64:
    runs-on: ubuntu-latest
    needs: [create-release]
    steps:
      - uses: actions/checkout@v3
      - id: build
        uses: ./.github/actions/release-build
        with:
          target: aarch64-unknown-linux-gnu
          github_token: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      sha256sum: ${{ steps.build.outputs.sha256sum }}

  build-x86_64:
    runs-on: ubuntu-latest
    needs: [create-release]
    steps:
      - uses: actions/checkout@v3
      - id: build
        uses: ./.github/actions/release-build
        with:
          target: x86_64-unknown-linux-gnu
          github_token: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      sha256sum: ${{ steps.build.outputs.sha256sum }}

  upload-checksum:
    runs-on: ubuntu-latest
    needs: [build-aarch64, build-x86_64]
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ${{ needs.build-aarch64.outputs.sha256sum }} >> SHA256SUMS.txt
          echo ${{ needs.build-x86_64.outputs.sha256sum }} >> SHA256SUMS.txt
          gh release upload ${{ github.ref_name }} SHA256SUMS.txt
