on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu,aarch64-unknown-linux-gnu
      - uses: Swatinem/rust-cache@v2
      - run: |
          cargo build --release --target aarch64-unknown-linux-gnu
          cargo build --release --target x86_64-unknown-linux-gnu
